const path = require("node:path");
const fs = require("node:fs");
const crypto = require("node:crypto");
const { rootNodeFromAnchor } = require("@codama/nodes-from-anchor");
const { readJson } = require("@codama/renderers-core");
const { visit, rootNodeVisitor } = require("@codama/visitors-core");
const { getRenderMapVisitor } = require("@codama/renderers-vixen-parser");
const { renderVisitor: renderRustVisitor } = require("@codama/renderers-rust");

/**
 * This script generates the Yellowstone Vixen parser from the idl.json file.
 * To run it: node generate-parser.js
 */

const projectName = "pumpfun";
const projectFolder = path.join(__dirname, projectName);
const idlPath = path.join(__dirname, "idls/pumpfun_idl.json");

if (!fs.existsSync(idlPath)) {
    console.error("Error: idl.json not found in the current directory.");
    process.exit(1);
}

const idl = readJson(idlPath);
const node = rootNodeFromAnchor(idl);

// Helper to generate events parser content
function generateEventsParser(idl) {
    if (!idl.events || idl.events.length === 0) return null;

    const events = idl.events;

    // Imports
    let content = `//! This code was AUTOGENERATED using the codama library (custom event parser).
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!

use crate::deserialize_checked;
use crate::generated_sdk::types::*;
use crate::ID;

`;

    // Enum Definition
    content += `#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "tracing", derive(strum_macros::Display))]
pub enum PumpProgramEvent {
`;
    events.forEach(evt => {
        content += `    ${evt.name}(${evt.name}),\n`;
    });
    content += `}\n\n`;

    // PumpProgramEvent impl
    content += `impl PumpProgramEvent {

    /// Internal parsing logic
    fn parse_from_discriminator(discriminator: &[u8; 8], data: &[u8]) -> Result<Option<Self>, std::io::Error> {
        match *discriminator {
`;

    events.forEach(evt => {
        const discStr = `[${evt.discriminator.join(', ')}]`;
        content += `            ${discStr} => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::${evt.name}(event)))
            }
`;
    });

    content += `            _ => Ok(None),
        }
    }
}

#[derive(Debug, Copy, Clone)]
pub struct EventParser;

impl yellowstone_vixen_core::Parser for EventParser {
    type Input = yellowstone_vixen_core::instruction::InstructionUpdate;
    type Output = PumpProgramEvent;

    fn id(&self) -> std::borrow::Cow<'static, str> {
        "Pump::EventParser".into()
    }

    fn prefilter(&self) -> yellowstone_vixen_core::Prefilter {
        yellowstone_vixen_core::Prefilter::builder()
            .transaction_accounts([ID])
            .build()
            .unwrap()
    }

    async fn parse(
        &self,
        ix_update: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<Self::Output> {
        if !ix_update.program.equals_ref(ID) {
            return Err(yellowstone_vixen_core::ParseError::Filtered);
        }

        let res = EventParser::parse_impl(ix_update);

        #[cfg(feature = "tracing")]
        if let Err(e) = &res {
            if ix_update.data.len() >= 8 {
                let ix_discriminator: [u8; 8] = ix_update.data[0..8]
                    .try_into()
                    .unwrap_or([0u8; 8]);

                tracing::info!(
                    name: "incorrectly_parsed_event",
                    name = "ix_update",
                    program = ID.to_string(),
                    event = "deserialization_error",
                    discriminator = ?ix_discriminator,
                    error = ?e
                );
            }
        }

        res
    }
}

impl yellowstone_vixen_core::ProgramParser for EventParser {
    #[inline]
    fn program_id(&self) -> yellowstone_vixen_core::Pubkey {
        ID.to_bytes().into()
    }
}

impl EventParser {
    /// Anchor event CPI discriminator
    const ANCHOR_EVENT_CPI_DISCRIMINATOR: [u8; 8] = [228, 69, 165, 46, 81, 203, 154, 29];

    pub(crate) fn parse_impl(
        ix: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<PumpProgramEvent> {
        // Anchor events are emitted via a CPI with format:
        // [8 bytes: anchor event discriminator] [8 bytes: event discriminator] [N bytes: event data]
        // Total minimum: 16 bytes
        if ix.data.len() < 16 {
            return Err(yellowstone_vixen_core::ParseError::from(
                "Event data too short: expected at least 16 bytes for Anchor event CPI",
            ));
        }

        // Check for Anchor event CPI discriminator
        let anchor_disc: [u8; 8] = ix.data[0..8].try_into()?;
        if anchor_disc != Self::ANCHOR_EVENT_CPI_DISCRIMINATOR {
            return Err(yellowstone_vixen_core::ParseError::Filtered);
        }

        // Skip Anchor prefix, read actual event discriminator
        let event_discriminator: [u8; 8] = ix.data[8..16].try_into()?;
        let event_data = &ix.data[16..];

        match PumpProgramEvent::parse_from_discriminator(&event_discriminator, event_data) {
            Ok(Some(event)) => {
                #[cfg(feature = "tracing")]
                tracing::info!(
                    name: "correctly_parsed_event",
                    name = "ix_update",
                    program = ID.to_string(),
                    event = event.to_string()
                );
                Ok(event)
            }
            Ok(None) => Err(yellowstone_vixen_core::ParseError::Filtered),
            Err(e) => Err(yellowstone_vixen_core::ParseError::from(e.to_string())),
        }
    }
}
`;
    return content;
}

// Custom generation logic to handle the Vixen renderer
const generator = rootNodeVisitor((root) => {
    console.log(`Generating Rust SDK and Parser in ${projectFolder}...`);

    // 1. Generate the base Rust SDK
    // This uses the standard Rust renderer which provides the Borsh structs for accounts and instructions.
    const rustVisitor = renderRustVisitor(path.join(projectFolder, "src", "generated_sdk"), {
        crateFolder: projectFolder,
        formatCode: false, // Set to true if you have rustfmt installed and want formatted code
    });
    visit(root, rustVisitor);

    // 2. Generate the Vixen-specific Parser logic
    // This produces the 'instructions_parser.rs' and 'accounts_parser.rs' that Vixen needs.
    const vixenVisitor = getRenderMapVisitor({
        projectFolder,
        projectName,
    });
    const renderMap = visit(root, vixenVisitor);

    // 3. Inject Events Parser
    const eventsContent = generateEventsParser(idl);
    if (eventsContent) {
        console.log("Generating events parser...");
        const eventsFile = 'src/generated_parser/events_parser.rs';
        renderMap.set(eventsFile, eventsContent);

        // Update mod.rs to include events_parser
        const modFile = 'src/generated_parser/mod.rs';
        let modContent = renderMap.get(modFile);
        if (modContent) {
            modContent += `\npub mod events_parser;\n`;
            renderMap.set(modFile, modContent);
        } else {
            // Backup if mod.rs isn't in renderMap
            const defaultMod = `pub mod instructions_parser;
pub mod accounts_parser;
pub mod events_parser;
`;
            renderMap.set(modFile, defaultMod);
        }
    }

    // 4. Write the files to disk manually
    // We do this manually to ensure all files are written correctly to the target folder.
    renderMap.forEach((content, fileName) => {
        const filePath = path.join(projectFolder, fileName);
        fs.mkdirSync(path.dirname(filePath), { recursive: true });
        if (content !== undefined) {
            fs.writeFileSync(filePath, content);
        }
    });

    console.log("Success! The parser has been generated.");
    console.log(`Location: ${projectFolder} `);
});

visit(node, generator);
