//! This code was AUTOGENERATED using the codama library (custom event parser).
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!

use crate::deserialize_checked;
use crate::generated_sdk::types::*;
use crate::ID;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "tracing", derive(strum_macros::Display))]
pub enum PumpProgramEvent {
    AdminSetCreatorEvent(AdminSetCreatorEvent),
    AdminSetIdlAuthorityEvent(AdminSetIdlAuthorityEvent),
    AdminUpdateTokenIncentivesEvent(AdminUpdateTokenIncentivesEvent),
    ClaimTokenIncentivesEvent(ClaimTokenIncentivesEvent),
    CloseUserVolumeAccumulatorEvent(CloseUserVolumeAccumulatorEvent),
    CollectCreatorFeeEvent(CollectCreatorFeeEvent),
    CompleteEvent(CompleteEvent),
    CompletePumpAmmMigrationEvent(CompletePumpAmmMigrationEvent),
    CreateEvent(CreateEvent),
    ExtendAccountEvent(ExtendAccountEvent),
    InitUserVolumeAccumulatorEvent(InitUserVolumeAccumulatorEvent),
    ReservedFeeRecipientsEvent(ReservedFeeRecipientsEvent),
    SetCreatorEvent(SetCreatorEvent),
    SetMetaplexCreatorEvent(SetMetaplexCreatorEvent),
    SetParamsEvent(SetParamsEvent),
    SyncUserVolumeAccumulatorEvent(SyncUserVolumeAccumulatorEvent),
    TradeEvent(TradeEvent),
    UpdateGlobalAuthorityEvent(UpdateGlobalAuthorityEvent),
}

impl PumpProgramEvent {

    /// Internal parsing logic
    fn parse_from_discriminator(discriminator: &[u8; 8], data: &[u8]) -> Result<Option<Self>, std::io::Error> {
        match *discriminator {
            [64, 69, 192, 104, 29, 30, 25, 107] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::AdminSetCreatorEvent(event)))
            }
            [245, 59, 70, 34, 75, 185, 109, 92] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::AdminSetIdlAuthorityEvent(event)))
            }
            [147, 250, 108, 120, 247, 29, 67, 222] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::AdminUpdateTokenIncentivesEvent(event)))
            }
            [79, 172, 246, 49, 205, 91, 206, 232] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::ClaimTokenIncentivesEvent(event)))
            }
            [146, 159, 189, 172, 146, 88, 56, 244] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::CloseUserVolumeAccumulatorEvent(event)))
            }
            [122, 2, 127, 1, 14, 191, 12, 175] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::CollectCreatorFeeEvent(event)))
            }
            [95, 114, 97, 156, 212, 46, 152, 8] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::CompleteEvent(event)))
            }
            [189, 233, 93, 185, 92, 148, 234, 148] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::CompletePumpAmmMigrationEvent(event)))
            }
            [27, 114, 169, 77, 222, 235, 99, 118] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::CreateEvent(event)))
            }
            [97, 97, 215, 144, 93, 146, 22, 124] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::ExtendAccountEvent(event)))
            }
            [134, 36, 13, 72, 232, 101, 130, 216] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::InitUserVolumeAccumulatorEvent(event)))
            }
            [43, 188, 250, 18, 221, 75, 187, 95] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::ReservedFeeRecipientsEvent(event)))
            }
            [237, 52, 123, 37, 245, 251, 72, 210] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::SetCreatorEvent(event)))
            }
            [142, 203, 6, 32, 127, 105, 191, 162] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::SetMetaplexCreatorEvent(event)))
            }
            [223, 195, 159, 246, 62, 48, 143, 131] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::SetParamsEvent(event)))
            }
            [197, 122, 167, 124, 116, 81, 91, 255] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::SyncUserVolumeAccumulatorEvent(event)))
            }
            [189, 219, 127, 211, 78, 230, 97, 238] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::TradeEvent(event)))
            }
            [182, 195, 137, 42, 35, 206, 207, 247] => {
                let event = deserialize_checked(data, discriminator)?;
                Ok(Some(PumpProgramEvent::UpdateGlobalAuthorityEvent(event)))
            }
            _ => Ok(None),
        }
    }
}

#[derive(Debug, Copy, Clone)]
pub struct EventParser;

impl yellowstone_vixen_core::Parser for EventParser {
    type Input = yellowstone_vixen_core::instruction::InstructionUpdate;
    type Output = PumpProgramEvent;

    fn id(&self) -> std::borrow::Cow<'static, str> {
        "Pump::EventParser".into()
    }

    fn prefilter(&self) -> yellowstone_vixen_core::Prefilter {
        yellowstone_vixen_core::Prefilter::builder()
            .transaction_accounts([ID])
            .build()
            .unwrap()
    }

    async fn parse(
        &self,
        ix_update: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<Self::Output> {
        if !ix_update.program.equals_ref(ID) {
            return Err(yellowstone_vixen_core::ParseError::Filtered);
        }

        let res = EventParser::parse_impl(ix_update);

        #[cfg(feature = "tracing")]
        if let Err(e) = &res {
            if ix_update.data.len() >= 8 {
                let ix_discriminator: [u8; 8] = ix_update.data[0..8]
                    .try_into()
                    .unwrap_or([0u8; 8]);

                tracing::info!(
                    name: "incorrectly_parsed_event",
                    name = "ix_update",
                    program = ID.to_string(),
                    event = "deserialization_error",
                    discriminator = ?ix_discriminator,
                    error = ?e
                );
            }
        }

        res
    }
}

impl yellowstone_vixen_core::ProgramParser for EventParser {
    #[inline]
    fn program_id(&self) -> yellowstone_vixen_core::Pubkey {
        ID.to_bytes().into()
    }
}

impl EventParser {
    /// Anchor event CPI discriminator
    const ANCHOR_EVENT_CPI_DISCRIMINATOR: [u8; 8] = [228, 69, 165, 46, 81, 203, 154, 29];

    pub(crate) fn parse_impl(
        ix: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<PumpProgramEvent> {
        // Anchor events are emitted via a CPI with format:
        // [8 bytes: anchor event discriminator] [8 bytes: event discriminator] [N bytes: event data]
        // Total minimum: 16 bytes
        if ix.data.len() < 16 {
            return Err(yellowstone_vixen_core::ParseError::from(
                "Event data too short: expected at least 16 bytes for Anchor event CPI",
            ));
        }

        // Check for Anchor event CPI discriminator
        let anchor_disc: [u8; 8] = ix.data[0..8].try_into()?;
        if anchor_disc != Self::ANCHOR_EVENT_CPI_DISCRIMINATOR {
            return Err(yellowstone_vixen_core::ParseError::Filtered);
        }

        // Skip Anchor prefix, read actual event discriminator
        let event_discriminator: [u8; 8] = ix.data[8..16].try_into()?;
        let event_data = &ix.data[16..];

        match PumpProgramEvent::parse_from_discriminator(&event_discriminator, event_data) {
            Ok(Some(event)) => {
                #[cfg(feature = "tracing")]
                tracing::info!(
                    name: "correctly_parsed_event",
                    name = "ix_update",
                    program = ID.to_string(),
                    event = event.to_string()
                );
                Ok(event)
            }
            Ok(None) => Err(yellowstone_vixen_core::ParseError::Filtered),
            Err(e) => Err(yellowstone_vixen_core::ParseError::from(e.to_string())),
        }
    }
}
