//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

// #[cfg(feature = "proto")]
pub mod proto_types_parsers {
    use yellowstone_vixen_core::proto_helper_traits;
    proto_helper_traits!();
    use crate::proto_def;

            use crate::types::AdminSetCreatorEvent;
        impl IntoProto<proto_def::AdminSetCreatorEvent> for AdminSetCreatorEvent {
            fn into_proto(self) -> proto_def::AdminSetCreatorEvent {
                proto_def::AdminSetCreatorEvent {
                                            timestamp: self.timestamp,
                                            admin_set_creator_authority: self.admin_set_creator_authority.to_string(),
                                            mint: self.mint.to_string(),
                                            bonding_curve: self.bonding_curve.to_string(),
                                            old_creator: self.old_creator.to_string(),
                                            new_creator: self.new_creator.to_string(),
                                    }
            }
        }   
            use crate::types::AdminSetIdlAuthorityEvent;
        impl IntoProto<proto_def::AdminSetIdlAuthorityEvent> for AdminSetIdlAuthorityEvent {
            fn into_proto(self) -> proto_def::AdminSetIdlAuthorityEvent {
                proto_def::AdminSetIdlAuthorityEvent {
                                            idl_authority: self.idl_authority.to_string(),
                                    }
            }
        }   
            use crate::types::AdminUpdateTokenIncentivesEvent;
        impl IntoProto<proto_def::AdminUpdateTokenIncentivesEvent> for AdminUpdateTokenIncentivesEvent {
            fn into_proto(self) -> proto_def::AdminUpdateTokenIncentivesEvent {
                proto_def::AdminUpdateTokenIncentivesEvent {
                                            start_time: self.start_time,
                                            end_time: self.end_time,
                                            day_number: self.day_number,
                                            token_supply_per_day: self.token_supply_per_day,
                                            mint: self.mint.to_string(),
                                            seconds_in_a_day: self.seconds_in_a_day,
                                            timestamp: self.timestamp,
                                    }
            }
        }   
            use crate::types::ClaimCashbackEvent;
        impl IntoProto<proto_def::ClaimCashbackEvent> for ClaimCashbackEvent {
            fn into_proto(self) -> proto_def::ClaimCashbackEvent {
                proto_def::ClaimCashbackEvent {
                                            user: self.user.to_string(),
                                            amount: self.amount,
                                            timestamp: self.timestamp,
                                            total_claimed: self.total_claimed,
                                            total_cashback_earned: self.total_cashback_earned,
                                    }
            }
        }   
            use crate::types::ClaimTokenIncentivesEvent;
        impl IntoProto<proto_def::ClaimTokenIncentivesEvent> for ClaimTokenIncentivesEvent {
            fn into_proto(self) -> proto_def::ClaimTokenIncentivesEvent {
                proto_def::ClaimTokenIncentivesEvent {
                                            user: self.user.to_string(),
                                            mint: self.mint.to_string(),
                                            amount: self.amount,
                                            timestamp: self.timestamp,
                                            total_claimed_tokens: self.total_claimed_tokens,
                                            current_sol_volume: self.current_sol_volume,
                                    }
            }
        }   
            use crate::types::CloseUserVolumeAccumulatorEvent;
        impl IntoProto<proto_def::CloseUserVolumeAccumulatorEvent> for CloseUserVolumeAccumulatorEvent {
            fn into_proto(self) -> proto_def::CloseUserVolumeAccumulatorEvent {
                proto_def::CloseUserVolumeAccumulatorEvent {
                                            user: self.user.to_string(),
                                            timestamp: self.timestamp,
                                            total_unclaimed_tokens: self.total_unclaimed_tokens,
                                            total_claimed_tokens: self.total_claimed_tokens,
                                            current_sol_volume: self.current_sol_volume,
                                            last_update_timestamp: self.last_update_timestamp,
                                    }
            }
        }   
            use crate::types::CollectCreatorFeeEvent;
        impl IntoProto<proto_def::CollectCreatorFeeEvent> for CollectCreatorFeeEvent {
            fn into_proto(self) -> proto_def::CollectCreatorFeeEvent {
                proto_def::CollectCreatorFeeEvent {
                                            timestamp: self.timestamp,
                                            creator: self.creator.to_string(),
                                            creator_fee: self.creator_fee,
                                    }
            }
        }   
            use crate::types::CompleteEvent;
        impl IntoProto<proto_def::CompleteEvent> for CompleteEvent {
            fn into_proto(self) -> proto_def::CompleteEvent {
                proto_def::CompleteEvent {
                                            user: self.user.to_string(),
                                            mint: self.mint.to_string(),
                                            bonding_curve: self.bonding_curve.to_string(),
                                            timestamp: self.timestamp,
                                    }
            }
        }   
            use crate::types::CompletePumpAmmMigrationEvent;
        impl IntoProto<proto_def::CompletePumpAmmMigrationEvent> for CompletePumpAmmMigrationEvent {
            fn into_proto(self) -> proto_def::CompletePumpAmmMigrationEvent {
                proto_def::CompletePumpAmmMigrationEvent {
                                            user: self.user.to_string(),
                                            mint: self.mint.to_string(),
                                            mint_amount: self.mint_amount,
                                            sol_amount: self.sol_amount,
                                            pool_migration_fee: self.pool_migration_fee,
                                            bonding_curve: self.bonding_curve.to_string(),
                                            timestamp: self.timestamp,
                                            pool: self.pool.to_string(),
                                    }
            }
        }   
            use crate::types::CreateEvent;
        impl IntoProto<proto_def::CreateEvent> for CreateEvent {
            fn into_proto(self) -> proto_def::CreateEvent {
                proto_def::CreateEvent {
                                            name: self.name,
                                            symbol: self.symbol,
                                            uri: self.uri,
                                            mint: self.mint.to_string(),
                                            bonding_curve: self.bonding_curve.to_string(),
                                            user: self.user.to_string(),
                                            creator: self.creator.to_string(),
                                            timestamp: self.timestamp,
                                            virtual_token_reserves: self.virtual_token_reserves,
                                            virtual_sol_reserves: self.virtual_sol_reserves,
                                            real_token_reserves: self.real_token_reserves,
                                            token_total_supply: self.token_total_supply,
                                            token_program: self.token_program.to_string(),
                                            is_mayhem_mode: self.is_mayhem_mode,
                                            is_cashback_enabled: self.is_cashback_enabled,
                                    }
            }
        }   
            use crate::types::DistributeCreatorFeesEvent;
        impl IntoProto<proto_def::DistributeCreatorFeesEvent> for DistributeCreatorFeesEvent {
            fn into_proto(self) -> proto_def::DistributeCreatorFeesEvent {
                proto_def::DistributeCreatorFeesEvent {
                                            timestamp: self.timestamp,
                                            mint: self.mint.to_string(),
                                            bonding_curve: self.bonding_curve.to_string(),
                                            sharing_config: self.sharing_config.to_string(),
                                            admin: self.admin.to_string(),
                                            shareholders: self.shareholders.into_iter().map(|x| x.into_proto()).collect(),
                                            distributed: self.distributed,
                                    }
            }
        }   
            use crate::types::ExtendAccountEvent;
        impl IntoProto<proto_def::ExtendAccountEvent> for ExtendAccountEvent {
            fn into_proto(self) -> proto_def::ExtendAccountEvent {
                proto_def::ExtendAccountEvent {
                                            account: self.account.to_string(),
                                            user: self.user.to_string(),
                                            current_size: self.current_size,
                                            new_size: self.new_size,
                                            timestamp: self.timestamp,
                                    }
            }
        }   
            use crate::types::FeeTier;
        impl IntoProto<proto_def::FeeTier> for FeeTier {
            fn into_proto(self) -> proto_def::FeeTier {
                proto_def::FeeTier {
                                            market_cap_lamports_threshold: self.market_cap_lamports_threshold.to_string(),
                                            fees: Some(self.fees.into_proto()),
                                    }
            }
        }   
            use crate::types::Fees;
        impl IntoProto<proto_def::Fees> for Fees {
            fn into_proto(self) -> proto_def::Fees {
                proto_def::Fees {
                                            lp_fee_bps: self.lp_fee_bps,
                                            protocol_fee_bps: self.protocol_fee_bps,
                                            creator_fee_bps: self.creator_fee_bps,
                                    }
            }
        }   
            use crate::types::InitUserVolumeAccumulatorEvent;
        impl IntoProto<proto_def::InitUserVolumeAccumulatorEvent> for InitUserVolumeAccumulatorEvent {
            fn into_proto(self) -> proto_def::InitUserVolumeAccumulatorEvent {
                proto_def::InitUserVolumeAccumulatorEvent {
                                            payer: self.payer.to_string(),
                                            user: self.user.to_string(),
                                            timestamp: self.timestamp,
                                    }
            }
        }   
            use crate::types::MigrateBondingCurveCreatorEvent;
        impl IntoProto<proto_def::MigrateBondingCurveCreatorEvent> for MigrateBondingCurveCreatorEvent {
            fn into_proto(self) -> proto_def::MigrateBondingCurveCreatorEvent {
                proto_def::MigrateBondingCurveCreatorEvent {
                                            timestamp: self.timestamp,
                                            mint: self.mint.to_string(),
                                            bonding_curve: self.bonding_curve.to_string(),
                                            sharing_config: self.sharing_config.to_string(),
                                            old_creator: self.old_creator.to_string(),
                                            new_creator: self.new_creator.to_string(),
                                    }
            }
        }   
            use crate::types::MinimumDistributableFeeEvent;
        impl IntoProto<proto_def::MinimumDistributableFeeEvent> for MinimumDistributableFeeEvent {
            fn into_proto(self) -> proto_def::MinimumDistributableFeeEvent {
                proto_def::MinimumDistributableFeeEvent {
                                            minimum_required: self.minimum_required,
                                            distributable_fees: self.distributable_fees,
                                            can_distribute: self.can_distribute,
                                    }
            }
        }   
            use crate::types::OptionBool;
        impl IntoProto<proto_def::OptionBool> for OptionBool {
            fn into_proto(self) -> proto_def::OptionBool {
                proto_def::OptionBool {
                                            value: self.value,
                                    }
            }
        }   
            use crate::types::ReservedFeeRecipientsEvent;
        impl IntoProto<proto_def::ReservedFeeRecipientsEvent> for ReservedFeeRecipientsEvent {
            fn into_proto(self) -> proto_def::ReservedFeeRecipientsEvent {
                proto_def::ReservedFeeRecipientsEvent {
                                            timestamp: self.timestamp,
                                            reserved_fee_recipient: self.reserved_fee_recipient.to_string(),
                                            reserved_fee_recipients: self.reserved_fee_recipients.into_iter().map(|x| x.to_string()).collect(),
                                    }
            }
        }   
            use crate::types::SetCreatorEvent;
        impl IntoProto<proto_def::SetCreatorEvent> for SetCreatorEvent {
            fn into_proto(self) -> proto_def::SetCreatorEvent {
                proto_def::SetCreatorEvent {
                                            timestamp: self.timestamp,
                                            mint: self.mint.to_string(),
                                            bonding_curve: self.bonding_curve.to_string(),
                                            creator: self.creator.to_string(),
                                    }
            }
        }   
            use crate::types::SetMetaplexCreatorEvent;
        impl IntoProto<proto_def::SetMetaplexCreatorEvent> for SetMetaplexCreatorEvent {
            fn into_proto(self) -> proto_def::SetMetaplexCreatorEvent {
                proto_def::SetMetaplexCreatorEvent {
                                            timestamp: self.timestamp,
                                            mint: self.mint.to_string(),
                                            bonding_curve: self.bonding_curve.to_string(),
                                            metadata: self.metadata.to_string(),
                                            creator: self.creator.to_string(),
                                    }
            }
        }   
            use crate::types::SetParamsEvent;
        impl IntoProto<proto_def::SetParamsEvent> for SetParamsEvent {
            fn into_proto(self) -> proto_def::SetParamsEvent {
                proto_def::SetParamsEvent {
                                            initial_virtual_token_reserves: self.initial_virtual_token_reserves,
                                            initial_virtual_sol_reserves: self.initial_virtual_sol_reserves,
                                            initial_real_token_reserves: self.initial_real_token_reserves,
                                            final_real_sol_reserves: self.final_real_sol_reserves,
                                            token_total_supply: self.token_total_supply,
                                            fee_basis_points: self.fee_basis_points,
                                            withdraw_authority: self.withdraw_authority.to_string(),
                                            enable_migrate: self.enable_migrate,
                                            pool_migration_fee: self.pool_migration_fee,
                                            creator_fee_basis_points: self.creator_fee_basis_points,
                                            fee_recipients: self.fee_recipients.into_iter().map(|x| x.to_string()).collect(),
                                            timestamp: self.timestamp,
                                            set_creator_authority: self.set_creator_authority.to_string(),
                                            admin_set_creator_authority: self.admin_set_creator_authority.to_string(),
                                    }
            }
        }   
            use crate::types::Shareholder;
        impl IntoProto<proto_def::Shareholder> for Shareholder {
            fn into_proto(self) -> proto_def::Shareholder {
                proto_def::Shareholder {
                                            address: self.address.to_string(),
                                            share_bps: self.share_bps.into(),
                                    }
            }
        }   
            use crate::types::SyncUserVolumeAccumulatorEvent;
        impl IntoProto<proto_def::SyncUserVolumeAccumulatorEvent> for SyncUserVolumeAccumulatorEvent {
            fn into_proto(self) -> proto_def::SyncUserVolumeAccumulatorEvent {
                proto_def::SyncUserVolumeAccumulatorEvent {
                                            user: self.user.to_string(),
                                            total_claimed_tokens_before: self.total_claimed_tokens_before,
                                            total_claimed_tokens_after: self.total_claimed_tokens_after,
                                            timestamp: self.timestamp,
                                    }
            }
        }   
            use crate::types::TradeEvent;
        impl IntoProto<proto_def::TradeEvent> for TradeEvent {
            fn into_proto(self) -> proto_def::TradeEvent {
                proto_def::TradeEvent {
                                            mint: self.mint.to_string(),
                                            sol_amount: self.sol_amount,
                                            token_amount: self.token_amount,
                                            is_buy: self.is_buy,
                                            user: self.user.to_string(),
                                            timestamp: self.timestamp,
                                            virtual_sol_reserves: self.virtual_sol_reserves,
                                            virtual_token_reserves: self.virtual_token_reserves,
                                            real_sol_reserves: self.real_sol_reserves,
                                            real_token_reserves: self.real_token_reserves,
                                            fee_recipient: self.fee_recipient.to_string(),
                                            fee_basis_points: self.fee_basis_points,
                                            fee: self.fee,
                                            creator: self.creator.to_string(),
                                            creator_fee_basis_points: self.creator_fee_basis_points,
                                            creator_fee: self.creator_fee,
                                            track_volume: self.track_volume,
                                            total_unclaimed_tokens: self.total_unclaimed_tokens,
                                            total_claimed_tokens: self.total_claimed_tokens,
                                            current_sol_volume: self.current_sol_volume,
                                            last_update_timestamp: self.last_update_timestamp,
                                            ix_name: self.ix_name,
                                            mayhem_mode: self.mayhem_mode,
                                            cashback_fee_basis_points: self.cashback_fee_basis_points,
                                            cashback: self.cashback,
                                    }
            }
        }   
            use crate::types::UpdateGlobalAuthorityEvent;
        impl IntoProto<proto_def::UpdateGlobalAuthorityEvent> for UpdateGlobalAuthorityEvent {
            fn into_proto(self) -> proto_def::UpdateGlobalAuthorityEvent {
                proto_def::UpdateGlobalAuthorityEvent {
                                            global: self.global.to_string(),
                                            authority: self.authority.to_string(),
                                            new_authority: self.new_authority.to_string(),
                                            timestamp: self.timestamp,
                                    }
            }
        }   
            use crate::types::UpdateMayhemVirtualParamsEvent;
        impl IntoProto<proto_def::UpdateMayhemVirtualParamsEvent> for UpdateMayhemVirtualParamsEvent {
            fn into_proto(self) -> proto_def::UpdateMayhemVirtualParamsEvent {
                proto_def::UpdateMayhemVirtualParamsEvent {
                                            timestamp: self.timestamp,
                                            mint: self.mint.to_string(),
                                            virtual_token_reserves: self.virtual_token_reserves,
                                            virtual_sol_reserves: self.virtual_sol_reserves,
                                            new_virtual_token_reserves: self.new_virtual_token_reserves,
                                            new_virtual_sol_reserves: self.new_virtual_sol_reserves,
                                            real_token_reserves: self.real_token_reserves,
                                            real_sol_reserves: self.real_sol_reserves,
                                    }
            }
        }   
    
    }

