//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum PumpError {
    /// 6000 - The given account is not authorized to execute this instruction.
    #[error("The given account is not authorized to execute this instruction.")]
    NotAuthorized = 0x1770,
    /// 6001 - The program is already initialized.
    #[error("The program is already initialized.")]
    AlreadyInitialized = 0x1771,
    /// 6002 - slippage: Too much SOL required to buy the given amount of tokens.
    #[error("slippage: Too much SOL required to buy the given amount of tokens.")]
    TooMuchSolRequired = 0x1772,
    /// 6003 - slippage: Too little SOL received to sell the given amount of tokens.
    #[error("slippage: Too little SOL received to sell the given amount of tokens.")]
    TooLittleSolReceived = 0x1773,
    /// 6004 - The mint does not match the bonding curve.
    #[error("The mint does not match the bonding curve.")]
    MintDoesNotMatchBondingCurve = 0x1774,
    /// 6005 - The bonding curve has completed and liquidity migrated to raydium.
    #[error("The bonding curve has completed and liquidity migrated to raydium.")]
    BondingCurveComplete = 0x1775,
    /// 6006 - The bonding curve has not completed.
    #[error("The bonding curve has not completed.")]
    BondingCurveNotComplete = 0x1776,
    /// 6007 - The program is not initialized.
    #[error("The program is not initialized.")]
    NotInitialized = 0x1777,
    /// 6008 - Withdraw too frequent
    #[error("Withdraw too frequent")]
    WithdrawTooFrequent = 0x1778,
    /// 6009 - new_size should be > current_size
    #[error("new_size should be > current_size")]
    NewSizeShouldBeGreaterThanCurrentSize = 0x1779,
    /// 6010 - Account type not supported
    #[error("Account type not supported")]
    AccountTypeNotSupported = 0x177A,
    /// 6011 - initial_real_token_reserves should be less than token_total_supply
    #[error("initial_real_token_reserves should be less than token_total_supply")]
    InitialRealTokenReservesShouldBeLessThanTokenTotalSupply = 0x177B,
    /// 6012 - initial_virtual_token_reserves should be greater than initial_real_token_reserves
    #[error("initial_virtual_token_reserves should be greater than initial_real_token_reserves")]
    InitialVirtualTokenReservesShouldBeGreaterThanInitialRealTokenReserves = 0x177C,
    /// 6013 - fee_basis_points greater than maximum
    #[error("fee_basis_points greater than maximum")]
    FeeBasisPointsGreaterThanMaximum = 0x177D,
    /// 6014 - Withdraw authority cannot be set to System Program ID
    #[error("Withdraw authority cannot be set to System Program ID")]
    AllZerosWithdrawAuthority = 0x177E,
    /// 6015 - pool_migration_fee should be less than final_real_sol_reserves
    #[error("pool_migration_fee should be less than final_real_sol_reserves")]
    PoolMigrationFeeShouldBeLessThanFinalRealSolReserves = 0x177F,
    /// 6016 - pool_migration_fee should be greater than creator_fee + MAX_MIGRATE_FEES
    #[error("pool_migration_fee should be greater than creator_fee + MAX_MIGRATE_FEES")]
    PoolMigrationFeeShouldBeGreaterThanCreatorFeePlusMaxMigrateFees = 0x1780,
    /// 6017 - Migrate instruction is disabled
    #[error("Migrate instruction is disabled")]
    DisabledWithdraw = 0x1781,
    /// 6018 - Migrate instruction is disabled
    #[error("Migrate instruction is disabled")]
    DisabledMigrate = 0x1782,
    /// 6019 - Invalid creator pubkey
    #[error("Invalid creator pubkey")]
    InvalidCreator = 0x1783,
    /// 6020 - Buy zero amount
    #[error("Buy zero amount")]
    BuyZeroAmount = 0x1784,
    /// 6021 - Not enough tokens to buy
    #[error("Not enough tokens to buy")]
    NotEnoughTokensToBuy = 0x1785,
    /// 6022 - Sell zero amount
    #[error("Sell zero amount")]
    SellZeroAmount = 0x1786,
    /// 6023 - Not enough tokens to sell
    #[error("Not enough tokens to sell")]
    NotEnoughTokensToSell = 0x1787,
    /// 6024 - Overflow
    #[error("Overflow")]
    Overflow = 0x1788,
    /// 6025 - Truncation
    #[error("Truncation")]
    Truncation = 0x1789,
    /// 6026 - Division by zero
    #[error("Division by zero")]
    DivisionByZero = 0x178A,
    /// 6027 - Not enough remaining accounts
    #[error("Not enough remaining accounts")]
    NotEnoughRemainingAccounts = 0x178B,
    /// 6028 - All fee recipients should be non-zero
    #[error("All fee recipients should be non-zero")]
    AllFeeRecipientsShouldBeNonZero = 0x178C,
    /// 6029 - Unsorted or not unique fee recipients
    #[error("Unsorted or not unique fee recipients")]
    UnsortedNotUniqueFeeRecipients = 0x178D,
    /// 6030 - Creator should not be zero
    #[error("Creator should not be zero")]
    CreatorShouldNotBeZero = 0x178E,
    /// 6031 - 
    #[error("")]
    StartTimeInThePast = 0x178F,
    /// 6032 - 
    #[error("")]
    EndTimeInThePast = 0x1790,
    /// 6033 - 
    #[error("")]
    EndTimeBeforeStartTime = 0x1791,
    /// 6034 - 
    #[error("")]
    TimeRangeTooLarge = 0x1792,
    /// 6035 - 
    #[error("")]
    EndTimeBeforeCurrentDay = 0x1793,
    /// 6036 - 
    #[error("")]
    SupplyUpdateForFinishedRange = 0x1794,
    /// 6037 - 
    #[error("")]
    DayIndexAfterEndIndex = 0x1795,
    /// 6038 - 
    #[error("")]
    DayInActiveRange = 0x1796,
    /// 6039 - 
    #[error("")]
    InvalidIncentiveMint = 0x1797,
    /// 6040 - Buy: Not enough SOL to cover for rent exemption.
    #[error("Buy: Not enough SOL to cover for rent exemption.")]
    BuyNotEnoughSolToCoverRent = 0x1798,
    /// 6041 - Buy: Not enough SOL to cover for fees.
    #[error("Buy: Not enough SOL to cover for fees.")]
    BuyNotEnoughSolToCoverFees = 0x1799,
    /// 6042 - Slippage: Would buy less tokens than expected min_tokens_out
    #[error("Slippage: Would buy less tokens than expected min_tokens_out")]
    BuySlippageBelowMinTokensOut = 0x179A,
    /// 6043 - 
    #[error("")]
    NameTooLong = 0x179B,
    /// 6044 - 
    #[error("")]
    SymbolTooLong = 0x179C,
    /// 6045 - 
    #[error("")]
    UriTooLong = 0x179D,
    /// 6046 - 
    #[error("")]
    CreateV2Disabled = 0x179E,
    /// 6047 - 
    #[error("")]
    CpitializeMayhemFailed = 0x179F,
    /// 6048 - 
    #[error("")]
    MayhemModeDisabled = 0x17A0,
    /// 6049 - creator has been migrated to sharing config, use pump_fees::reset_fee_sharing_config instead
    #[error("creator has been migrated to sharing config, use pump_fees::reset_fee_sharing_config instead")]
    CreatorMigratedToSharingConfig = 0x17A1,
    /// 6050 - creator_vault has been migrated to sharing config, use pump:distribute_creator_fees instead
    #[error("creator_vault has been migrated to sharing config, use pump:distribute_creator_fees instead")]
    UnableToDistributeCreatorVaultMigratedToSharingConfig = 0x17A2,
    /// 6051 - Sharing config is not active
    #[error("Sharing config is not active")]
    SharingConfigNotActive = 0x17A3,
    /// 6052 - The recipient account is executable, so it cannot receive lamports, remove it from the team first
    #[error("The recipient account is executable, so it cannot receive lamports, remove it from the team first")]
    UnableToDistributeCreatorFeesToExecutableRecipient = 0x17A4,
    /// 6053 - Bonding curve creator does not match sharing config
    #[error("Bonding curve creator does not match sharing config")]
    BondingCurveAndSharingConfigCreatorMismatch = 0x17A5,
    /// 6054 - Remaining accounts do not match shareholders, make sure to pass exactly the same pubkeys in the same order
    #[error("Remaining accounts do not match shareholders, make sure to pass exactly the same pubkeys in the same order")]
    ShareholdersAndRemainingAccountsMismatch = 0x17A6,
    /// 6055 - Share bps must be greater than 0
    #[error("Share bps must be greater than 0")]
    InvalidShareBps = 0x17A7,
    /// 6056 - Cashback is not enabled
    #[error("Cashback is not enabled")]
    CashbackNotEnabled = 0x17A8,
}

impl From<PumpError> for solana_program_error::ProgramError {
    fn from(e: PumpError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

