//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateMayhemVirtualParamsEvent {
pub timestamp: i64,
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub mint: Pubkey,
pub virtual_token_reserves: u64,
pub virtual_sol_reserves: u64,
pub new_virtual_token_reserves: u64,
pub new_virtual_sol_reserves: u64,
pub real_token_reserves: u64,
pub real_sol_reserves: u64,
}


